apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: quarkus-person-app-dr
spec:
  host: quarkus-person-app
  subsets:
    - name: v1
      labels:
        app.kubernetes.io/version: v1
    - name: v2
      labels:
        app.kubernetes.io/version: v2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: quarkus-person-app-vs
spec:
  hosts:
#    - quarkus-person-app
    - "*"
  gateways:
    - microservices-gateway
  http:
#    - match:
#        - headers:
#            X-Version:
#              exact: v2
#      route:
#        - destination:
#            host: quarkus-person-app
#            subset: v2
    - match:
      - uri:
          prefix: "/person"
      rewrite:
        uri: " "
      route:
        - destination:
            host: quarkus-person-app
            subset: v1
          weight: 90
        - destination:
            host: quarkus-person-app
            subset: v2
          weight: 10